
name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (Node 20)
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Switch from 16 to 20

      - name: Verify Node.js version
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
